name: build android explorer

description: build android explorer apk

inputs:
  abi-list:
    description: The abi list of the sdk to publish
    required: false
    default: 'armeabi-v7a'
  build-params:
    description: Set project properties for gradle when building explorer
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Python Setup
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install Common Dependencies
      uses: ./lynx/.github/actions/common-deps
    - name: Build Explorer App
      shell: bash
      run: |-
        cd $GITHUB_WORKSPACE/lynx
        source tools/envsetup.sh
        pushd explorer/android
        ./gradlew :LynxExplorer:assembleNoasanRelease -Penable_trace=perfetto -PabiList=${{ inputs.abi-list }} -no-daemon ${{ inputs.build-params }}
        popd
    - name: upload artifact
      uses: lynx-infra/upload-artifact@332ec52e99f7cbf1fbbdc9bcc09280d49147d092
      continue-on-error: true
      with:
        name: android-lynx-explorer
        path: '${{ github.workspace }}/lynx/explorer/android/lynx_explorer/build/outputs/apk/noasan/release/LynxExplorer-noasan-release.apk'
