name: install windows common dependencies

description: pull common source and binary dependencies via habitat for windows.

inputs:
  concurrency:
    description: concurrency of requests
    default: '2'
    required: false
  cache-backend:
    description: cache backend for habitat
    default: 'lynx-infra'
    required: false
  target:
    description: habitat target
    default: ''
    required: false
  # actions/cache stores files with relative directory, which causes inconsistency between self-hosted runner and
  # container runner. Therefore, add this temporary option to modify cache key prefix as a workaround. Delete this when
  # we are able to adjust the container runner's directory structure to the same as self-hosted runner.
  cache-key-prefix:
    description: cache key prefix for cache action
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: Get habitat cache key
      id: hab
      shell: pwsh
      run: |
        if ([string]::IsNullOrEmpty("${{ inputs.target }}")) {
          python lynx/tools/ci/habitat_cache_helper.py
        } else {
          python lynx/tools/ci/habitat_cache_helper.py --target ${{ inputs.target }}
        }
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    - name: Get habitat cache directory
      id: hab-cache-dir
      shell: pwsh
      run: |
        $habitat_cache_dir = python -c "import os; import tempfile; print(os.path.join(os.environ.get('HOME', tempfile.gettempdir()), '.habitat_cache'))"
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        echo "HABITAT_CACHE_DIR=$habitat_cache_dir" >> ${env:GITHUB_OUTPUT}

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: pwsh
      run: |
        $npm_cache_dir = python -c "import os; import pathlib; print(os.path.join(pathlib.Path.home(), '.local', 'share', 'pnpm', 'store'))"
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        echo "NPM_CACHE_DIR=$npm_cache_dir" >> ${env:GITHUB_OUTPUT}

    - name: Get Python Cache Directory
      id: pip
      shell: pwsh
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      run: |
        $cache = python -m pip cache dir
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        $correctPath = (Get-Item $cache).FullName
        echo "PIP_CACHE_DIR=$correctPath" >> ${env:GITHUB_OUTPUT}

    - name: Setup cache action
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.hab-cache-dir.outputs.HABITAT_CACHE_DIR }}
        key: hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-${{ steps.hab.outputs.HABITAT_DEPS_FILE_DIGEST }}
        restore-keys: |
          hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-

    - name: Setup cache action
      if: ${{ inputs.cache-backend == 'github' }}
      uses: actions/cache@v5
      with:
        path: ${{ steps.hab-cache-dir.outputs.HABITAT_CACHE_DIR }}
        key: hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-${{ steps.hab.outputs.HABITAT_DEPS_FILE_DIGEST }}
        restore-keys: |
          hab-${{ runner.os }}-${{ steps.hab.outputs.HABITAT_TARGETS }}-

    - name: Python Requirements Cache
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.pip.outputs.PIP_CACHE_DIR }}
        key: pip${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('lynx/tools/vpython_tools/requirements.txt', 'lynx/testing/integration_test/test_script/requirements.txt') }}
        restore-keys: |
          pip${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: Cache pnpm Dependencies
      if: ${{ inputs.cache-backend == 'lynx-infra' && inputs.cache-key-prefix == '' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        # set pnpm store path to a specific value since we can't get it via `pnpm store path` before pnpm is setup.
        path: ${{ steps.npm-cache-dir.outputs.NPM_CACHE_DIR }}
        key: pnpm-${{ runner.os }}-${{ hashFiles('lynx/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-

    - name: Install Python dependencies
      shell: pwsh
      run: |
        python -m pip install -r lynx/tools/vpython_tools/requirements.txt
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
        python -m pip install -r lynx/testing/integration_test/test_script/requirements.txt
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    - name: run habitat sync
      shell: pwsh
      working-directory: lynx
      run: |
        if ([string]::IsNullOrEmpty("${{ inputs.target }}")) {
            .\tools\hab.ps1 sync .
        } else {
            .\tools\hab.ps1 sync . --target ${{ inputs.target }}
        }
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
        npm_config_store_dir: ${{ steps.npm-cache-dir.outputs.NPM_CACHE_DIR }}
