name: lynx_core_publish

on: workflow_dispatch

jobs:
  lynx_types_publish:
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download Source
        uses: actions/checkout@v6
        with:
          path: lynx
      - name: Python Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install Common Dependencies
        uses: ./lynx/.github/actions/common-deps
        with:
          cache-backend: github
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: |-
          cd $GITHUB_WORKSPACE/lynx
          source tools/envsetup.sh
          pushd js_libraries/lynx-runtime-shared
          npm run build
          popd
          pushd js_libraries/lynx-core
          npm run build:web
          popd
      - name: Publish
        run: |-
          cd $GITHUB_WORKSPACE/lynx/js_libraries/lynx-core
          npm publish --access public --provenance
